server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:

# 타임리프를 사용할 예정이므로 생략
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: root
    password: qwer1234

  jpa:
    open-in-view: true
    hibernate:
#      create 설정 시, 데이터 초기화
      ddl-auto: update
      naming:
#        hibernate의 테이블 생성 시, 변수명 그대로 DB 테이블에 필드를 생성
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      jpa의 기본전략이 아닌 MySQL의 전략을 따름
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
#    콘솔에 sql 출력
    show-sql: true
    properties:
#      콘솔에 sql 개행해서 예쁘게 출력
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
